### ISSUE TITLE
Null poiner exception in AudioFileHeader

### ISSUE THREAD

**Issue by volodkuzn** [trousev/cleer#29]
When we tried to use this lib, is falls with fatal exception on some composition.

**Comment by trousev** [comment]
Please provide full stack trace or at least mp3 examples, which fails to run.

Also, please, tell whad do You do exactly? Scan library with this mp3?

**Comment by trousev** [comment]
Well, figured it out finally.

Problem was: some files just don't have ID3 tags. Implemented some 'fallback' in b0f5a66b684ed0c245c39ddd48a4cfd0f30faad2
